import { RouteInfo } from '../sidebar.metadata';

export const items: RouteInfo[] = [
  {
    path: '/coach-dashboard',
    title: 'Dashboard',
    iconType: 'feather',
    icon: 'grid',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/clients',
    title: 'Clients',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/clients/client-workouts',
    title: 'Workouts',
    iconType: 'feather',
    icon: 'zap',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '',
    title: 'Admin',
    iconType: 'feather',
    icon: 'shield',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/users',
        title: 'Users Management',
        iconType: 'feather',
        icon: 'users',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/subscriptions',
        title: 'Subscriptions',
        iconType: 'feather',
        icon: 'credit-card',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/clients/client-nutrition',
    title: 'Nutrition',
    iconType: 'feather',
    icon: 'heart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '',
    title: 'Workout',
    iconType: 'feather',
    icon: 'zap',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH', 'ROLE_ADMIN'],
    submenu: [
      {
        path: '/workout/program-library',
        title: 'Program Library',
        iconType: 'feather',
        icon: 'folder',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/workout/exercise-library',
        title: 'Exercise Library',
        iconType: 'feather',
        icon: 'target',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Nutrition',
    iconType: 'feather',
    icon: 'heart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/nutrition/plans',
        title: 'Plans',
        iconType: 'feather',
        icon: 'clipboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/custom-foods',
        title: 'Custom Foods',
        iconType: 'feather',
        icon: 'plus-circle',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/days',
        title: 'Days',
        iconType: 'feather',
        icon: 'calendar',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/meals',
        title: 'Meals',
        iconType: 'feather',
        icon: 'coffee',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Nutrition',
    iconType: 'feather',
    icon: 'heart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/nutrition/plans',
        title: 'Plans',
        iconType: 'feather',
        icon: 'clipboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/custom-foods',
        title: 'Custom Foods',
        iconType: 'feather',
        icon: 'plus-circle',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/chat',
    title: 'Chat',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: 'assignments/me',
    title: 'My Check-ins',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: 'forms/manage-checkins',
    title: 'Manage Check-ins',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/calendar',
    title: 'Calendar',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '',
    title: 'Forms',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/forms',
        title: 'Check-in Forms',
        iconType: 'feather',
        icon: 'clipboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/configuration',
    title: 'Settings',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '',
    title: 'Websites',
    iconType: 'feather',
    icon: 'layout',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/websites/create',
        title: 'Create Website',
        iconType: 'feather',
        icon: 'edit-3',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/websites/leads',
        title: 'Website Leads',
        iconType: 'feather',
        icon: 'inbox',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'body-measurements',
    title: 'Body Measurements',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: 'progress-pictures',
    title: 'Progress pictures',
    iconType: 'feather',
    icon: 'camera',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
];
