import { RouteInfo } from '../sidebar.metadata';

export const items: RouteInfo[] = [
  {
    path: '/coach-dashboard',
    title: 'DASHBOARD',
    iconType: 'feather',
    icon: 'layout-dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/clients',
    title: 'CLIENTS',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/clients/client-workouts',
    title: 'WORKOUTS',
    iconType: 'feather',
    icon: 'dumbbell',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '',
    title: 'ADMIN',
    iconType: 'feather',
    icon: 'shield',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/users',
        title: 'USERS_MANAGEMENT',
        iconType: 'feather',
        icon: 'users',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/subscriptions',
        title: 'SUBSCRIPTIONS',
        iconType: 'feather',
        icon: 'credit-card',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/clients/client-nutrition',
    title: 'NUTRITION',
    iconType: 'feather',
    icon: 'apple',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '/tasks', title: 'TASKS', iconType: 'feather', icon: 'check-square',
    class: '', groupTitle: false, badge: '', badgeClass: '', submenu: [], roles: ['ROLE_CLIENT'],
  },
  {
    path: '',
    title: 'WORKOUT',
    iconType: 'feather',
    icon: 'dumbbell',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH', 'ROLE_ADMIN'],
    submenu: [
      {
        path: '/workout/program-library',
        title: 'SIDEBAR_PROGRAMS',
        iconType: 'feather',
        icon: 'folder',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/workout/exercise-library',
        title: 'EXERCISE_LIBRARY',
        iconType: 'feather',
        icon: 'target',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'NUTRITION',
    iconType: 'feather',
    icon: 'apple',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/nutrition/plans',
        title: 'SIDEBAR_MEAL_PLANS',
        iconType: 'feather',
        icon: 'clipboard-list',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/custom-foods',
        title: 'SIDEBAR_FOODS',
        iconType: 'feather',
        icon: 'plus-circle',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/food-replacement-groups',
        title: 'SIDEBAR_FOOD_REPLACEMENTS',
        iconType: 'feather',
        icon: 'arrow-left-right',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/meals',
        title: 'MEALS',
        iconType: 'feather',
        icon: 'utensils',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'NUTRITION',
    iconType: 'feather',
    icon: 'apple',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/nutrition/plans',
        title: 'SIDEBAR_MEAL_PLANS',
        iconType: 'feather',
        icon: 'clipboard-list',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/custom-foods',
        title: 'SIDEBAR_FOODS',
        iconType: 'feather',
        icon: 'plus-circle',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'SIDEBAR_CHECK_INS',
    iconType: 'feather',
    icon: 'clipboard-list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/forms',
        title: 'SIDEBAR_TEMPLATES',
        iconType: 'feather',
        icon: 'file-check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'forms/manage-checkins',
        title: 'CLIENT_CHECK_INS',
        iconType: 'feather',
        icon: 'list-checks',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/calendar',
    title: 'CALENDAR',
    iconType: 'feather',
    icon: 'calendar-days',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/chat',
    title: 'CHAT',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH', 'ROLE_CLIENT'],
  },
  {
    path: 'assignments/me',
    title: 'MY_CHECK_INS',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '/theme',
    title: 'SIDEBAR_BRANDING',
    iconType: 'feather',
    icon: 'palette',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    // SUB-37
    path: '/subscription',
    title: 'MY_SUBSCRIPTION',
    iconType: 'feather',
    icon: 'credit-card',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/configuration',
    title: 'SETTINGS',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH', 'ROLE_CLIENT', 'ROLE_ADMIN'],
  },
  {
    path: '',
    title: 'SIDEBAR_BUSINESS',
    iconType: 'feather',
    icon: 'trending-up',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/grow/contact-form',
        title: 'CONTACT_FORM',
        iconType: 'feather',
        icon: 'mail',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/websites/create',
        title: 'COACH_WEBSITE',
        iconType: 'feather',
        icon: 'globe',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/websites/leads',
        title: 'LEADS',
        iconType: 'feather',
        icon: 'user-plus',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'body-measurements',
    title: 'BODY_MEASUREMENTS',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: 'progress-pictures',
    title: 'PROGRESS_PICTURES',
    iconType: 'feather',
    icon: 'camera',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
];
