import { RouteInfo } from '../sidebar.metadata';

export const items: RouteInfo[] = [
  {
    path: '/coach-dashboard',
    title: 'DASHBOARD',
    iconType: 'feather',
    icon: 'grid',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/clients',
    title: 'CLIENTS',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/clients/client-workouts',
    title: 'WORKOUTS',
    iconType: 'feather',
    icon: 'zap',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '',
    title: 'ADMIN',
    iconType: 'feather',
    icon: 'shield',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/users',
        title: 'USERS_MANAGEMENT',
        iconType: 'feather',
        icon: 'users',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/subscriptions',
        title: 'SUBSCRIPTIONS',
        iconType: 'feather',
        icon: 'credit-card',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/clients/client-nutrition',
    title: 'NUTRITION',
    iconType: 'feather',
    icon: 'heart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '',
    title: 'WORKOUT',
    iconType: 'feather',
    icon: 'zap',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH', 'ROLE_ADMIN'],
    submenu: [
      {
        path: '/workout/program-library',
        title: 'PROGRAM_LIBRARY',
        iconType: 'feather',
        icon: 'folder',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/workout/exercise-library',
        title: 'EXERCISE_LIBRARY',
        iconType: 'feather',
        icon: 'target',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'NUTRITION',
    iconType: 'feather',
    icon: 'heart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/nutrition/plans',
        title: 'PLANS',
        iconType: 'feather',
        icon: 'clipboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/custom-foods',
        title: 'CUSTOM_FOODS',
        iconType: 'feather',
        icon: 'plus-circle',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/food-replacement-groups',
        title: 'FOOD_REPLACEMENT_GROUPS',
        iconType: 'feather',
        icon: 'shuffle',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/meals',
        title: 'MEALS',
        iconType: 'feather',
        icon: 'coffee',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'NUTRITION',
    iconType: 'feather',
    icon: 'heart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/nutrition/plans',
        title: 'PLANS',
        iconType: 'feather',
        icon: 'clipboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/nutrition/custom-foods',
        title: 'CUSTOM_FOODS',
        iconType: 'feather',
        icon: 'plus-circle',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/chat',
    title: 'CHAT',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH', 'ROLE_CLIENT'],
  },
  {
    path: 'assignments/me',
    title: 'MY_CHECK_INS',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: '/calendar',
    title: 'CALENDAR',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '',
    title: 'FORMS',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/forms',
        title: 'CHECK_IN_TEMPLATES',
        iconType: 'feather',
        icon: 'clipboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'forms/manage-checkins',
        title: 'CLIENT_CHECK_INS',
        iconType: 'feather',
        icon: 'message-square',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/theme',
    title: 'THEME',
    iconType: 'feather',
    icon: 'sliders',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH'],
  },
  {
    path: '/configuration',
    title: 'SETTINGS',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_COACH', 'ROLE_CLIENT', 'ROLE_ADMIN'],
  },
  {
    path: '',
    title: 'GROW',
    iconType: 'feather',
    icon: 'layout',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    roles: ['ROLE_COACH'],
    submenu: [
      {
        path: '/grow/contact-form',
        title: 'CONTACT_FORM',
        iconType: 'feather',
        icon: 'file-text',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/websites/create',
        title: 'COACH_WEBSITE',
        iconType: 'feather',
        icon: 'edit-3',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/websites/leads',
        title: 'LEADS',
        iconType: 'feather',
        icon: 'inbox',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'body-measurements',
    title: 'BODY_MEASUREMENTS',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
  {
    path: 'progress-pictures',
    title: 'PROGRESS_PICTURES',
    iconType: 'feather',
    icon: 'camera',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ['ROLE_CLIENT'],
  },
];
